<?php
/**
 * GetInventoryUnitResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  SMS\Suppliers
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Supplier API
 *
 * This documentation describes SMS Suppliers API. To be able use this API you should have an api-key and api-username
 *
 * Contact: sms.tech@kaufland-online.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace SMS\Suppliers\Model\v2;

use \ArrayAccess;
use \SMS\Suppliers\ObjectSerializer;

/**
 * GetInventoryUnitResponse Class Doc Comment
 *
 * @category Class
 * @package  SMS\Suppliers
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class GetInventoryUnitResponse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'GetInventoryUnitResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'item_id' => 'int',
        'condition' => 'string',
        'ean' => 'string',
        'quantity' => 'int',
        'minimal_order_volume' => 'int',
        'supplier_item_id' => 'string',
        'is_hauler_delivery' => 'bool',
        'origin_manufacturer_country' => 'string',
        'country_values' => 'object'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'item_id' => 'int64',
        'condition' => null,
        'ean' => null,
        'quantity' => 'int64',
        'minimal_order_volume' => 'int64',
        'supplier_item_id' => null,
        'is_hauler_delivery' => null,
        'origin_manufacturer_country' => null,
        'country_values' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'item_id' => 'item_id',
        'condition' => 'condition',
        'ean' => 'ean',
        'quantity' => 'quantity',
        'minimal_order_volume' => 'minimal_order_volume',
        'supplier_item_id' => 'supplier_item_id',
        'is_hauler_delivery' => 'is_hauler_delivery',
        'origin_manufacturer_country' => 'origin_manufacturer_country',
        'country_values' => 'country_values'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'item_id' => 'setItemId',
        'condition' => 'setCondition',
        'ean' => 'setEan',
        'quantity' => 'setQuantity',
        'minimal_order_volume' => 'setMinimalOrderVolume',
        'supplier_item_id' => 'setSupplierItemId',
        'is_hauler_delivery' => 'setIsHaulerDelivery',
        'origin_manufacturer_country' => 'setOriginManufacturerCountry',
        'country_values' => 'setCountryValues'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'item_id' => 'getItemId',
        'condition' => 'getCondition',
        'ean' => 'getEan',
        'quantity' => 'getQuantity',
        'minimal_order_volume' => 'getMinimalOrderVolume',
        'supplier_item_id' => 'getSupplierItemId',
        'is_hauler_delivery' => 'getIsHaulerDelivery',
        'origin_manufacturer_country' => 'getOriginManufacturerCountry',
        'country_values' => 'getCountryValues'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const CONDITION__NEW = 'new';
    const CONDITION_AS_NEW = 'as_new';
    const CONDITION_VERY_GOOD = 'very_good';
    const CONDITION_GOOD = 'good';
    const CONDITION_ACCEPTABLE = 'acceptable';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getConditionAllowableValues()
    {
        return [
            self::CONDITION__NEW,
            self::CONDITION_AS_NEW,
            self::CONDITION_VERY_GOOD,
            self::CONDITION_GOOD,
            self::CONDITION_ACCEPTABLE,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['item_id'] = isset($data['item_id']) ? $data['item_id'] : null;
        $this->container['condition'] = isset($data['condition']) ? $data['condition'] : null;
        $this->container['ean'] = isset($data['ean']) ? $data['ean'] : null;
        $this->container['quantity'] = isset($data['quantity']) ? $data['quantity'] : null;
        $this->container['minimal_order_volume'] = isset($data['minimal_order_volume']) ? $data['minimal_order_volume'] : null;
        $this->container['supplier_item_id'] = isset($data['supplier_item_id']) ? $data['supplier_item_id'] : null;
        $this->container['is_hauler_delivery'] = isset($data['is_hauler_delivery']) ? $data['is_hauler_delivery'] : null;
        $this->container['origin_manufacturer_country'] = isset($data['origin_manufacturer_country']) ? $data['origin_manufacturer_country'] : null;
        $this->container['country_values'] = isset($data['country_values']) ? $data['country_values'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['item_id'] === null) {
            $invalidProperties[] = "'item_id' can't be null";
        }
        if ($this->container['condition'] === null) {
            $invalidProperties[] = "'condition' can't be null";
        }
        $allowedValues = $this->getConditionAllowableValues();
        if (!is_null($this->container['condition']) && !in_array($this->container['condition'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'condition', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['ean'] === null) {
            $invalidProperties[] = "'ean' can't be null";
        }
        if ($this->container['quantity'] === null) {
            $invalidProperties[] = "'quantity' can't be null";
        }
        if ($this->container['minimal_order_volume'] === null) {
            $invalidProperties[] = "'minimal_order_volume' can't be null";
        }
        if ($this->container['supplier_item_id'] === null) {
            $invalidProperties[] = "'supplier_item_id' can't be null";
        }
        if ($this->container['is_hauler_delivery'] === null) {
            $invalidProperties[] = "'is_hauler_delivery' can't be null";
        }
        if ($this->container['origin_manufacturer_country'] === null) {
            $invalidProperties[] = "'origin_manufacturer_country' can't be null";
        }
        if ($this->container['country_values'] === null) {
            $invalidProperties[] = "'country_values' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets item_id
     *
     * @return int
     */
    public function getItemId()
    {
        return $this->container['item_id'];
    }

    /**
     * Sets item_id
     *
     * @param int $item_id Item ID
     *
     * @return $this
     */
    public function setItemId($item_id)
    {
        $this->container['item_id'] = $item_id;

        return $this;
    }

    /**
     * Gets condition
     *
     * @return string
     */
    public function getCondition()
    {
        return $this->container['condition'];
    }

    /**
     * Sets condition
     *
     * @param string $condition Unit condition
     *
     * @return $this
     */
    public function setCondition($condition)
    {
        $allowedValues = $this->getConditionAllowableValues();
        if (!in_array($condition, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'condition', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['condition'] = $condition;

        return $this;
    }

    /**
     * Gets ean
     *
     * @return string
     */
    public function getEan()
    {
        return $this->container['ean'];
    }

    /**
     * Sets ean
     *
     * @param string $ean EAN
     *
     * @return $this
     */
    public function setEan($ean)
    {
        $this->container['ean'] = $ean;

        return $this;
    }

    /**
     * Gets quantity
     *
     * @return int
     */
    public function getQuantity()
    {
        return $this->container['quantity'];
    }

    /**
     * Sets quantity
     *
     * @param int $quantity Unit Quantity
     *
     * @return $this
     */
    public function setQuantity($quantity)
    {
        $this->container['quantity'] = $quantity;

        return $this;
    }

    /**
     * Gets minimal_order_volume
     *
     * @return int
     */
    public function getMinimalOrderVolume()
    {
        return $this->container['minimal_order_volume'];
    }

    /**
     * Sets minimal_order_volume
     *
     * @param int $minimal_order_volume Minimal Order Volume
     *
     * @return $this
     */
    public function setMinimalOrderVolume($minimal_order_volume)
    {
        $this->container['minimal_order_volume'] = $minimal_order_volume;

        return $this;
    }

    /**
     * Gets supplier_item_id
     *
     * @return string
     */
    public function getSupplierItemId()
    {
        return $this->container['supplier_item_id'];
    }

    /**
     * Sets supplier_item_id
     *
     * @param string $supplier_item_id Supplier Item ID / SKU
     *
     * @return $this
     */
    public function setSupplierItemId($supplier_item_id)
    {
        $this->container['supplier_item_id'] = $supplier_item_id;

        return $this;
    }

    /**
     * Gets is_hauler_delivery
     *
     * @return bool
     */
    public function getIsHaulerDelivery()
    {
        return $this->container['is_hauler_delivery'];
    }

    /**
     * Sets is_hauler_delivery
     *
     * @param bool $is_hauler_delivery If this unit required a hauler delivery
     *
     * @return $this
     */
    public function setIsHaulerDelivery($is_hauler_delivery)
    {
        $this->container['is_hauler_delivery'] = $is_hauler_delivery;

        return $this;
    }

    /**
     * Gets origin_manufacturer_country
     *
     * @return string
     */
    public function getOriginManufacturerCountry()
    {
        return $this->container['origin_manufacturer_country'];
    }

    /**
     * Sets origin_manufacturer_country
     *
     * @param string $origin_manufacturer_country IsoAlpha2 code of the manufacturing country
     *
     * @return $this
     */
    public function setOriginManufacturerCountry($origin_manufacturer_country)
    {
        $this->container['origin_manufacturer_country'] = $origin_manufacturer_country;

        return $this;
    }

    /**
     * Gets country_values
     *
     * @return object
     */
    public function getCountryValues()
    {
        return $this->container['country_values'];
    }

    /**
     * Sets country_values
     *
     * @param object $country_values country_values
     *
     * @return $this
     */
    public function setCountryValues($country_values)
    {
        $this->container['country_values'] = $country_values;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


