<?php
/**
 * GetInventoryUnitCountryValueResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SMS\Suppliers
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Supplier API
 *
 * This documentation describes SMS Suppliers API. To be able use this API you should have an api-key and api-username
 *
 * Contact: sms.tech@kaufland-online.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SMS\Suppliers;

/**
 * GetInventoryUnitCountryValueResponseTest Class Doc Comment
 *
 * @category    Class
 * @description GetInventoryUnitCountryValueResponse
 * @package     SMS\Suppliers
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetInventoryUnitCountryValueResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GetInventoryUnitCountryValueResponse"
     */
    public function testGetInventoryUnitCountryValueResponse()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "freight_costs"
     */
    public function testPropertyFreightCosts()
    {
    }

    /**
     * Test attribute "handling_costs"
     */
    public function testPropertyHandlingCosts()
    {
    }

    /**
     * Test attribute "return_shipping_costs"
     */
    public function testPropertyReturnShippingCosts()
    {
    }

    /**
     * Test attribute "delivery_min_time"
     */
    public function testPropertyDeliveryMinTime()
    {
    }

    /**
     * Test attribute "delivery_max_time"
     */
    public function testPropertyDeliveryMaxTime()
    {
    }
}
