<?php
/**
 * GetFulfilmentOrderUnitResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SMS\Suppliers
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Supplier API
 *
 * This documentation describes SMS Suppliers API. To be able use this API you should have an api-key and api-username
 *
 * OpenAPI spec version: 1.9.0
 * Contact: sms.tech@real-digital.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SMS\Suppliers;

/**
 * GetFulfilmentOrderUnitResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description GetFulfilmentOrderUnitResponse
/**
 * @package     SMS\Suppliers
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetFulfilmentOrderUnitResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GetFulfilmentOrderUnitResponse"
     */
    public function testGetFulfilmentOrderUnitResponse()
    {
    }

    /**
     * Test attribute "id_order_unit"
     */
    public function testPropertyIdOrderUnit()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "condition"
     */
    public function testPropertyCondition()
    {
    }

    /**
     * Test attribute "handling_costs"
     */
    public function testPropertyHandlingCosts()
    {
    }

    /**
     * Test attribute "freight_costs"
     */
    public function testPropertyFreightCosts()
    {
    }

    /**
     * Test attribute "cancel_reason"
     */
    public function testPropertyCancelReason()
    {
    }

    /**
     * Test attribute "is_cancelled"
     */
    public function testPropertyIsCancelled()
    {
    }

    /**
     * Test attribute "item"
     */
    public function testPropertyItem()
    {
    }

    /**
     * Test attribute "sku"
     */
    public function testPropertySku()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "delivery_time_expires"
     */
    public function testPropertyDeliveryTimeExpires()
    {
    }

    /**
     * Test attribute "customer_order_unit_status"
     */
    public function testPropertyCustomerOrderUnitStatus()
    {
    }
}
