<?php
/**
 * GetFulfilmentOrderResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SMS\Suppliers
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Supplier API
 *
 * This documentation describes SMS Suppliers API. To be able use this API you should have an api-key and api-username
 *
 * OpenAPI spec version: 1.3.0
 * Contact: sms.tech@real-digital.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SMS\Suppliers;

/**
 * GetFulfilmentOrderResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description GetFulfilmentOrderResponse
/**
 * @package     SMS\Suppliers
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetFulfilmentOrderResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GetFulfilmentOrderResponse"
     */
    public function testGetFulfilmentOrderResponse()
    {
    }

    /**
     * Test attribute "id_order"
     */
    public function testPropertyIdOrder()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "units"
     */
    public function testPropertyUnits()
    {
    }

    /**
     * Test attribute "shipment_address"
     */
    public function testPropertyShipmentAddress()
    {
    }
}
