<?php
/**
 * GetInventoryByIDResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Suppliers\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SMS API
 *
 * This documentation describes SMS API. To use this API you should have an api-key and api-username
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Suppliers\Api;

/**
 * GetInventoryByIDResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description GetInventoryByIDResponse
/**
 * @package     Suppliers\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetInventoryByIDResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "GetInventoryByIDResponse"
     */
    public function testGetInventoryByIDResponse()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "gln"
     */
    public function testPropertyGln()
    {

    }

    /**
     * Test attribute "delivery_note_required"
     */
    public function testPropertyDeliveryNoteRequired()
    {

    }

    /**
     * Test attribute "manager"
     */
    public function testPropertyManager()
    {

    }

}
