<?php
/**
 * GetInventoryUnitsByInventoryIDResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Suppliers\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SMS API
 *
 * This documentation describes SMS API. To use this API you should have an api-key and api-username
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Suppliers\Api;

/**
 * GetInventoryUnitsByInventoryIDResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description GetInventoryUnitsByInventoryIDResponse
/**
 * @package     Suppliers\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetInventoryUnitsByInventoryIDResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "GetInventoryUnitsByInventoryIDResponse"
     */
    public function testGetInventoryUnitsByInventoryIDResponse()
    {

    }

    /**
     * Test attribute "item_id"
     */
    public function testPropertyItemId()
    {

    }

    /**
     * Test attribute "condition"
     */
    public function testPropertyCondition()
    {

    }

    /**
     * Test attribute "ean"
     */
    public function testPropertyEan()
    {

    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {

    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {

    }

    /**
     * Test attribute "unit_id"
     */
    public function testPropertyUnitId()
    {

    }

    /**
     * Test attribute "inventory_id"
     */
    public function testPropertyInventoryId()
    {

    }

    /**
     * Test attribute "supplier_item_id"
     */
    public function testPropertySupplierItemId()
    {

    }

    /**
     * Test attribute "minimal_order_volume"
     */
    public function testPropertyMinimalOrderVolume()
    {

    }

    /**
     * Test attribute "shipping_cost"
     */
    public function testPropertyShippingCost()
    {

    }

    /**
     * Test attribute "delivery_min_time"
     */
    public function testPropertyDeliveryMinTime()
    {

    }

    /**
     * Test attribute "delivery_max_time"
     */
    public function testPropertyDeliveryMaxTime()
    {

    }

    /**
     * Test attribute "is_hauler_delivery"
     */
    public function testPropertyIsHaulerDelivery()
    {

    }

}
