<?php
/**
 * InventoryUnitApiTest
 * PHP version 5
 *
 * @category Class
 * @package  SMS\Suppliers
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Supplier API SDK
 *
 * This documentation describes SMS Suppliers API. To be able use this API you should have an api-key and api-username
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sms.tech@real-digital.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace SMS\Suppliers;

use \SMS\Suppliers\Configuration;
use \SMS\Suppliers\ApiClient;
use \SMS\Suppliers\ApiException;
use \SMS\Suppliers\ObjectSerializer;

/**
 * InventoryUnitApiTest Class Doc Comment
 *
 * @category Class
 * @package  SMS\Suppliers
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InventoryUnitApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteInventoryUnit
     *
     * Delete inventory unit by ID.
     *
     */
    public function testDeleteInventoryUnit()
    {
    }

    /**
     * Test case for getInventoryUnit
     *
     * Find inventory unit by ID.
     *
     */
    public function testGetInventoryUnit()
    {
    }

    /**
     * Test case for updateInventoryUnit
     *
     * Update inventory unit.
     *
     */
    public function testUpdateInventoryUnit()
    {
    }
}
