<?php
/**
 * OrderApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Suppliers\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SMS API
 *
 * This documentation describes SMS API. To use this API you should have an api-key and api-username
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Suppliers\Api;

use \Suppliers\Api\Configuration;
use \Suppliers\Api\ApiClient;
use \Suppliers\Api\ApiException;
use \Suppliers\Api\ObjectSerializer;

/**
 * OrderApiTest Class Doc Comment
 *
 * @category Class
 * @package  Suppliers\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrderApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for cancelOrder
     *
     * Cancel whole order.
     *
     */
    public function testCancelOrder()
    {

    }

    /**
     * Test case for confirmOrder
     *
     * Confirm order.
     *
     */
    public function testConfirmOrder()
    {

    }

    /**
     * Test case for getOrderByID
     *
     * Find order by ID.
     *
     */
    public function testGetOrderByID()
    {

    }

}
