<?php
/**
 * OrderUnitApiTest
 * PHP version 5
 *
 * @category Class
 * @package  SMS\Suppliers
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Supplier API
 *
 * This documentation describes SMS Suppliers API. To be able use this API you should have an api-key and api-username
 *
 * Contact: sms.tech@kaufland-online.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace SMS\Suppliers\Tests\Api\v2;

use \SMS\Suppliers\Configuration;
use \SMS\Suppliers\ApiException;
use \SMS\Suppliers\ObjectSerializer;

/**
 * OrderUnitApiTest Class Doc Comment
 *
 * @category Class
 * @package  SMS\Suppliers
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrderUnitApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for cancelOrderUnit
     *
     * Cancel an order unit.
     *
     */
    public function testCancelOrderUnit()
    {
    }

    /**
     * Test case for getOrderUnit
     *
     * Find order unit by ID.
     *
     */
    public function testGetOrderUnit()
    {
    }

    /**
     * Test case for pickOrderUnit
     *
     * Change order unit status to 'picking'.
     *
     */
    public function testPickOrderUnit()
    {
    }

    /**
     * Test case for sendOrderUnit
     *
     * Send an order unit.
     *
     */
    public function testSendOrderUnit()
    {
    }

    /**
     * Test case for updateOrderUnitShipment
     *
     * Update shipment data of the order unit.
     *
     */
    public function testUpdateOrderUnitShipment()
    {
    }
}
