<?php
/**
 * SubscriptionApiTest
 * PHP version 5
 *
 * @category Class
 * @package  SMS\Suppliers
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Supplier API
 *
 * This documentation describes SMS Suppliers API. To be able use this API you should have an api-key and api-username
 *
 * Contact: sms.tech@kaufland-online.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace SMS\Suppliers\Tests\Api\v2;

use \SMS\Suppliers\Configuration;
use \SMS\Suppliers\ApiException;
use \SMS\Suppliers\ObjectSerializer;

/**
 * SubscriptionApiTest Class Doc Comment
 *
 * @category Class
 * @package  SMS\Suppliers
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SubscriptionApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createSubscription
     *
     * Create new subscription.
     *
     */
    public function testCreateSubscription()
    {
    }

    /**
     * Test case for deleteSubscription
     *
     * Delete existing subscription.
     *
     */
    public function testDeleteSubscription()
    {
    }

    /**
     * Test case for updateSubscription
     *
     * Update existing subscription.
     *
     */
    public function testUpdateSubscription()
    {
    }

    /**
     * Test case for viewSubscription
     *
     * View existing subscription.
     *
     */
    public function testViewSubscription()
    {
    }

    /**
     * Test case for viewSubscriptions
     *
     * Get all existing subscriptions.
     *
     */
    public function testViewSubscriptions()
    {
    }
}
